# Generated by Django 2.1.5 on 2019-02-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
