# Generated by Django 2.1.3 on 2018-12-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('paymentDate', models.DateTimeField(auto_now=True)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='Orders.Orders')),
            ],
        ),
    ]
