# Generated by Django 2.1.3 on 2018-12-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategories',
            name='catId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proCat', to='Categories.Categories'),
        ),
    ]
