# Generated by Django 2.1.3 on 2018-12-20 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
                ('deleteCart', models.BooleanField(default=False)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('cartProductId', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField()),
                ('deleteCartProduct', models.BooleanField(default=False)),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartProducts', to='Cart.Cart')),
                ('proVarId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurrentInCart', to='Products.ProductCombinations')),
            ],
        ),
    ]
