# Generated by Django 2.1.3 on 2019-01-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_offerproductvendors_offerprice'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CurrentInCart', to='Products.Products'),
            preserve_default=False,
        ),
    ]
