# Generated by Django 2.1.3 on 2019-01-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cartproducts_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='proVarId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CurrentInCart', to='Products.ProductCombinations'),
        ),
    ]
