# Generated by Django 2.1.3 on 2018-12-20 11:03

import User.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaId', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=5, default=300.0, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=5, default=300.0, max_digits=15)),
                ('areaImg', models.ImageField(upload_to='')),
                ('deliverCharge', models.DecimalField(decimal_places=2, default=200.0, max_digits=6)),
                ('deleteArea', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CashBack',
            fields=[
                ('cashBackId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField()),
                ('isUsed', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
                ('deleteCashBack', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPromoCodes',
            fields=[
                ('customerPromoCodeId', models.AutoField(primary_key=True, serialize=False)),
                ('deleteCustomerPromocode', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
                ('isUsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('promoCodeId', models.AutoField(primary_key=True, serialize=False)),
                ('promoCode', models.CharField(max_length=20)),
                ('discountType', models.IntegerField()),
                ('discountValue', models.DecimalField(decimal_places=2, max_digits=5)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField()),
                ('minPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isForAll', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Royality',
            fields=[
                ('royalityId', models.AutoField(primary_key=True, serialize=False)),
                ('royality', models.CharField(max_length=20)),
                ('subscribeCharge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('royalityDesc', models.CharField(max_length=200)),
                ('isLive', models.BooleanField(default=True)),
                ('deleteRoyality', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsedPromoCodes',
            fields=[
                ('usedPromoCodeId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('userAddressId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=5, default=300.0, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=5, default=400.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('verificationId', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('dateOfJoin', models.DateTimeField(auto_now=True)),
                ('isRoyality', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='User.Area')),
                ('royalityId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to='User.Royality')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', User.models.MyUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='verification',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificationCode', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedpromocodes',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsedPromoCodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedpromocodes',
            name='promoCodeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsedCustomers', to='User.PromoCodes'),
        ),
        migrations.AddField(
            model_name='customerpromocodes',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PromoCodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerpromocodes',
            name='promoCodeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to='User.PromoCodes'),
        ),
        migrations.AddField(
            model_name='cashback',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CashBacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
