# Generated by Django 2.1.3 on 2018-12-27 14:01

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='code',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='customerId',
        ),
        migrations.AddField(
            model_name='verification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verification',
            name='otp',
            field=models.CharField(default='0', editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+94777777777', editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
