# Generated by Django 2.1.3 on 2018-12-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20181227_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
