# Generated by Django 2.1.3 on 2019-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20181229_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
