# Generated by Django 2.1.3 on 2019-01-14 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20190114_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 14, 15, 37, 11, 896816, tzinfo=utc), editable=False),
        ),
    ]
