# Generated by Django 2.1.3 on 2019-01-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20190114_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocodes',
            name='isLive',
            field=models.BooleanField(default=True),
        ),
    ]
