# Generated by Django 2.1.5 on 2019-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20190120_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='deleteAddress',
            field=models.BooleanField(default=False),
        ),
    ]
