# Generated by Django 2.1.3 on 2019-01-22 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='dueCostPrice',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='dueSellPrice',
        ),
        migrations.AlterField(
            model_name='orders',
            name='promoCodeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='User.PromoCodes'),
        ),
    ]
