# Generated by Django 2.1.5 on 2019-02-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20190201_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='discountPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
