# Generated by Django 2.1.5 on 2019-02-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_auto_20190205_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='discountPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
