# Generated by Django 2.1.3 on 2018-12-20 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categories', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinationValues',
            fields=[
                ('combValueId', models.AutoField(primary_key=True, serialize=False)),
                ('isLive', models.BooleanField(default=True)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FreeOffer',
            fields=[
                ('freeOfferId', models.AutoField(primary_key=True, serialize=False)),
                ('offerName', models.CharField(max_length=50)),
                ('offerDesc', models.CharField(max_length=500)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('deleteOffer', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeProducts',
            fields=[
                ('freeProductId', models.AutoField(primary_key=True, serialize=False)),
                ('deleteFreeProduct', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
                ('freeOfferId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FreeProducts', to='Products.FreeOffer')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offerId', models.AutoField(primary_key=True, serialize=False)),
                ('offerTitle', models.CharField(max_length=20)),
                ('startDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField()),
                ('deleteOffer', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfferProductVendors',
            fields=[
                ('offerProductVendorId', models.AutoField(primary_key=True, serialize=False)),
                ('deleteOfferPro', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=False)),
                ('offerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Products.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCombinationImages',
            fields=[
                ('proVarImgId', models.AutoField(primary_key=True, serialize=False)),
                ('proVarImg', models.ImageField(height_field='height_field', upload_to='ProductImages/', width_field='width_field')),
                ('deleteImg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCombinationKeywords',
            fields=[
                ('proKeyId', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50)),
                ('deleteKeyword', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCombinations',
            fields=[
                ('combinationId', models.AutoField(primary_key=True, serialize=False)),
                ('isLive', models.BooleanField(default=True)),
                ('isStock', models.BooleanField(default=True)),
                ('deleteComb', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productTitle', models.CharField(max_length=50)),
                ('productDesc', models.CharField(max_length=1000)),
                ('hasVariants', models.BooleanField(default=False)),
                ('dateOfAdded', models.DateTimeField(auto_now=True)),
                ('brandId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Categories.Brands')),
                ('catId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Categories.Categories')),
                ('proCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Categories.ProductCategories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVendor',
            fields=[
                ('proVendorId', models.AutoField(primary_key=True, serialize=False)),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('isStock', models.BooleanField(default=False)),
                ('deleteProVendor', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
                ('dateOfAdded', models.DateTimeField(auto_now=True)),
                ('proVarId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Products.ProductCombinations')),
                ('vendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RainCheck',
            fields=[
                ('rainCheckId', models.AutoField(primary_key=True, serialize=False)),
                ('deleteRainCheck', models.BooleanField(default=False)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RainChecks', to=settings.AUTH_USER_MODEL)),
                ('productVendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RainChecks', to='Products.ProductVendor')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=500)),
                ('deleteReview', models.BooleanField(default=False)),
                ('isLive', models.BooleanField(default=True)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='Products.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('varId', models.AutoField(primary_key=True, serialize=False)),
                ('variantTitle', models.CharField(max_length=20)),
                ('deleteVariant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VariantValues',
            fields=[
                ('varValId', models.AutoField(primary_key=True, serialize=False)),
                ('varValue', models.CharField(max_length=20)),
                ('deleteVarValue', models.BooleanField(default=False)),
                ('varId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VariantVal', to='Products.Variants')),
            ],
        ),
        migrations.AddField(
            model_name='productcombinations',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Combinations', to='Products.Products'),
        ),
        migrations.AddField(
            model_name='productcombinationkeywords',
            name='proVarId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Keywords', to='Products.ProductCombinations'),
        ),
        migrations.AddField(
            model_name='productcombinationimages',
            name='proVarId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='Products.ProductCombinations'),
        ),
        migrations.AddField(
            model_name='offerproductvendors',
            name='proVendorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Offers', to='Products.ProductVendor'),
        ),
        migrations.AddField(
            model_name='freeproducts',
            name='freeProVendorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FreeProducts', to='Products.ProductVendor'),
        ),
        migrations.AddField(
            model_name='freeoffer',
            name='proVendorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FreeOffers', to='Products.ProductVendor'),
        ),
        migrations.AddField(
            model_name='combinationvalues',
            name='proCombId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combValues', to='Products.ProductCombinations'),
        ),
        migrations.AddField(
            model_name='combinationvalues',
            name='variantValue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Variants', to='Products.VariantValues'),
        ),
    ]
