# Generated by Django 2.1.3 on 2018-12-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20181222_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombinationimages',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='Products.Products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcombinationkeywords',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Keywords', to='Products.Products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvendor',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Products.Products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcombinationimages',
            name='proVarId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='Products.ProductCombinations'),
        ),
        migrations.AlterField(
            model_name='productcombinationkeywords',
            name='proVarId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Keywords', to='Products.ProductCombinations'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='proVarId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Products.ProductCombinations'),
        ),
    ]
