# Generated by Django 2.1.3 on 2019-01-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20181225_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproductvendors',
            name='offerPrice',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
            preserve_default=False,
        ),
    ]
