# Generated by Django 2.1.5 on 2019-01-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_review_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deletePro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='isLive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
